const express = require("express");
const router = express.Router();
const { getProducts, getProduct, createProduct, updateProduct, deleteProduct, getMyProducts, askQuestion, answerQuestion } = require("../controllers/productController");
const { protect, sellerOrAdmin, optionalAuth } = require("../middleware/authMiddleware");
const { getProductReviews } = require("../controllers/reviewController");
router.get("/", optionalAuth, getProducts);
router.get("/seller/my-products", protect, getMyProducts);
router.get("/:id", optionalAuth, getProduct);
router.post("/", protect, sellerOrAdmin, createProduct);
router.put("/:id", protect, sellerOrAdmin, updateProduct);
router.delete("/:id", protect, sellerOrAdmin, deleteProduct);
router.post("/:id/ask-question", protect, askQuestion);
router.patch("/:id/questions/:qid/answer", protect, answerQuestion);
router.get("/:id/reviews", getProductReviews);
module.exports = router;
