/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ShopsIdRouteImport } from './routes/shops.$id'
import { Route as SellerVerificationStatusRouteImport } from './routes/seller.verification-status'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerPayoutsRouteImport } from './routes/seller.payouts'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerOnboardingRouteImport } from './routes/seller.onboarding'
import { Route as SellerHeritageRouteImport } from './routes/seller.heritage'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as HeritageIdRouteImport } from './routes/heritage.$id'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountRequestAdminRouteImport } from './routes/account.request-admin'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ShopsIdRoute = ShopsIdRouteImport.update({
  id: '/shops/$id',
  path: '/shops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerVerificationStatusRoute =
  SellerVerificationStatusRouteImport.update({
    id: '/verification-status',
    path: '/verification-status',
    getParentRoute: () => SellerRoute,
  } as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPayoutsRoute = SellerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SellerRoute,
} as any)
const SellerHeritageRoute = SellerHeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const HeritageIdRoute = HeritageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HeritageRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRequestAdminRoute = AccountRequestAdminRouteImport.update({
  id: '/request-admin',
  path: '/request-admin',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/refunds': typeof RefundsRoute
  '/regions': typeof RegionsRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/request-admin': typeof AccountRequestAdminRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/heritage/$id': typeof HeritageIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/heritage': typeof SellerHeritageRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/verification-status': typeof SellerVerificationStatusRoute
  '/shops/$id': typeof ShopsIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/refunds': typeof RefundsRoute
  '/regions': typeof RegionsRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/sell': typeof SellRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/request-admin': typeof AccountRequestAdminRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/heritage/$id': typeof HeritageIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/heritage': typeof SellerHeritageRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/verification-status': typeof SellerVerificationStatusRoute
  '/shops/$id': typeof ShopsIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/refunds': typeof RefundsRoute
  '/regions': typeof RegionsRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/request-admin': typeof AccountRequestAdminRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/heritage/$id': typeof HeritageIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/heritage': typeof SellerHeritageRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/verification-status': typeof SellerVerificationStatusRoute
  '/shops/$id': typeof ShopsIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/heritage'
    | '/login'
    | '/press'
    | '/privacy'
    | '/products'
    | '/refunds'
    | '/regions'
    | '/register'
    | '/resources'
    | '/sell'
    | '/seller'
    | '/shipping'
    | '/terms'
    | '/verification'
    | '/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/request-admin'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/heritage/$id'
    | '/products/$id'
    | '/seller/analytics'
    | '/seller/heritage'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/products'
    | '/seller/settings'
    | '/seller/verification-status'
    | '/shops/$id'
    | '/account/'
    | '/admin/'
    | '/seller/'
    | '/account/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/heritage'
    | '/login'
    | '/press'
    | '/privacy'
    | '/products'
    | '/refunds'
    | '/regions'
    | '/register'
    | '/resources'
    | '/sell'
    | '/shipping'
    | '/terms'
    | '/verification'
    | '/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/request-admin'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/heritage/$id'
    | '/products/$id'
    | '/seller/analytics'
    | '/seller/heritage'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/products'
    | '/seller/settings'
    | '/seller/verification-status'
    | '/shops/$id'
    | '/account'
    | '/admin'
    | '/seller'
    | '/account/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/heritage'
    | '/login'
    | '/press'
    | '/privacy'
    | '/products'
    | '/refunds'
    | '/regions'
    | '/register'
    | '/resources'
    | '/sell'
    | '/seller'
    | '/shipping'
    | '/terms'
    | '/verification'
    | '/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/request-admin'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/heritage/$id'
    | '/products/$id'
    | '/seller/analytics'
    | '/seller/heritage'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/products'
    | '/seller/settings'
    | '/seller/verification-status'
    | '/shops/$id'
    | '/account/'
    | '/admin/'
    | '/seller/'
    | '/account/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HeritageRoute: typeof HeritageRouteWithChildren
  LoginRoute: typeof LoginRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RefundsRoute: typeof RefundsRoute
  RegionsRoute: typeof RegionsRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRouteWithChildren
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  WishlistRoute: typeof WishlistRoute
  ShopsIdRoute: typeof ShopsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shops/$id': {
      id: '/shops/$id'
      path: '/shops/$id'
      fullPath: '/shops/$id'
      preLoaderRoute: typeof ShopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/verification-status': {
      id: '/seller/verification-status'
      path: '/verification-status'
      fullPath: '/seller/verification-status'
      preLoaderRoute: typeof SellerVerificationStatusRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/payouts': {
      id: '/seller/payouts'
      path: '/payouts'
      fullPath: '/seller/payouts'
      preLoaderRoute: typeof SellerPayoutsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/heritage': {
      id: '/seller/heritage'
      path: '/heritage'
      fullPath: '/seller/heritage'
      preLoaderRoute: typeof SellerHeritageRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/heritage/$id': {
      id: '/heritage/$id'
      path: '/$id'
      fullPath: '/heritage/$id'
      preLoaderRoute: typeof HeritageIdRouteImport
      parentRoute: typeof HeritageRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/request-admin': {
      id: '/account/request-admin'
      path: '/request-admin'
      fullPath: '/account/request-admin'
      preLoaderRoute: typeof AccountRequestAdminRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountRequestAdminRoute: typeof AccountRequestAdminRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountRequestAdminRoute: AccountRequestAdminRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HeritageRouteChildren {
  HeritageIdRoute: typeof HeritageIdRoute
}

const HeritageRouteChildren: HeritageRouteChildren = {
  HeritageIdRoute: HeritageIdRoute,
}

const HeritageRouteWithChildren = HeritageRoute._addFileChildren(
  HeritageRouteChildren,
)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SellerRouteChildren {
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerHeritageRoute: typeof SellerHeritageRoute
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPayoutsRoute: typeof SellerPayoutsRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerVerificationStatusRoute: typeof SellerVerificationStatusRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerHeritageRoute: SellerHeritageRoute,
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPayoutsRoute: SellerPayoutsRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerVerificationStatusRoute: SellerVerificationStatusRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BrandsRoute: BrandsRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HeritageRoute: HeritageRouteWithChildren,
  LoginRoute: LoginRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RefundsRoute: RefundsRoute,
  RegionsRoute: RegionsRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRouteWithChildren,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  WishlistRoute: WishlistRoute,
  ShopsIdRoute: ShopsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
